pipeline
{
    agent none
        stages
        {
            stage('Build')
            {
                agent any
                steps
                {
                    sh '''
                    echo "Hi"
                    sleep 5
                    '''
                }
            }

            stage('DEPLOY') {
            agent { label 'slave1' } 
            steps {
                echo "This is a DEPLOY stage"
                sh 'sleep 5'
            }
        }

            stage('Testing')
            {
                agent { label 'slave2' }
                steps 
                {
                    sh '''
                    echo "Bye"
                    '''
                }
            }

        }
}