pipeline
{
    agent none
        stages
        {
            stage('Build')
            {
                agent any
                steps
                {
                    sh '''
                    echo "Hi"
                    sleep 5
                    '''
                }
            }

            satge('Deploy')
            {
                agent { label 'slave1' }
                steps 
                {
                    sh '''
                    echo "Hello"
                    sleep 5
                    '''
                    
                }

            }

            stage('Testing')
            {
                agent { label 'slave2' }
                steps 
                {
                    sh '''
                    echo "Bye"
                    '''
                }
            }

        }
}