pipeline{
    agent{
        stages{
            stage('Build')
            steps{
            sh '''
            echo "Hi this Build stage"
            pwd
            '''
            }
        }
        stages{
        stage('Deploy')
        steps{
        sh '''
        echo "Hi this Deploy stage"
        pwd
        '''
        }
        }
        stages{
            stage('Test')
            steps{
            sh '''
            echo "Hi this is Test sthage"
            pwd
            '''
            }
            }
        }
    }
}